# Google OAuth Configuration
google.client.id=400541723028-g12aoud1lg2v5bbvchtg87ikor527k3d.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:8888/callback
google.auth.scope=email profile 
